The IMDB and Reuters (and MNIST) problems are examples of classification

Decide a particular class from a finite number of possibilities

They are discrete problems

The IMDB and Reuters (and MNIST) problems are examples of single label classification: decide a particular class from a finite number of possibilities. They are 'discrete' problems.

**Regression** problems, on the other hand, are continuous

E.g. Predicting tomorrow's temperature, the time to run a marathon or... 

**Regression** problems, on the other hand, are continuous. For example, Predicting tomorrow's temperature, the time to run a marathon or... 

1970s house prices in a Boston suburb 

1970s house prices in a Boston suburb. The problem is continuous because houses can have (almost) any price - house price is (essentially) a continuous variable.

The Boston housing dataset

The aim is the prediction of the median house price on the basis of knowledge of local property tax, crime rate, rooms per dwelling, accesibility to highways and nine other features


The aim, for the Boston housing dataset, is the prediction of the median house price on the basis of knowledge of local property tax, crime rate, rooms per dwelling, accesibility to highways and nine other features.

There are only 506 data samples, split into 404 training and 102 test 

Furthermore, each feature has a different scale

Some features are values in $[0, 1]$, some in $[1, 12]$, some in $[0, 100]$

There are only 506 data samples, split into 404 training and 102 test and furthermore, each feature has a different scale. Some features are values in $[0, 1]$, some in $[1, 12]$, some in $[0, 100]$.

In [1]:
from tensorflow.keras.datasets import boston_housing

(train_data, train_targets), (test_data, test_targets) = boston_housing.load_data()
print(train_data.shape, test_data.shape)

(404, 13) (102, 13)


There are 404 and 102 samples in training and test sets, and each label has 13 numerical features

In [2]:
print(train_data[0])

[  1.23247   0.        8.14      0.        0.538     6.142    91.7
   3.9769    4.      307.       21.      396.9      18.72   ]


The first sample.

In [3]:
train_targets[:10] # in 1000's

array([15.2, 42.3, 50. , 21.1, 17.7, 18.5, 11.3, 15.6, 15.6, 14.4])

The targets of the first ten samples in thousands of dollars.

In [4]:
for row in range(10):
    for col in range(8):
        x = train_data[row, col]        
        print("{:10.4f}".format(x), end='')
    print('\n') 

    1.2325    0.0000    8.1400    0.0000    0.5380    6.1420   91.7000    3.9769

    0.0218   82.5000    2.0300    0.0000    0.4150    7.6100   15.7000    6.2700

    4.8982    0.0000   18.1000    0.0000    0.6310    4.9700  100.0000    1.3325

    0.0396    0.0000    5.1900    0.0000    0.5150    6.0370   34.5000    5.9853

    3.6931    0.0000   18.1000    0.0000    0.7130    6.3760   88.4000    2.5671

    0.2839    0.0000    7.3800    0.0000    0.4930    5.7080   74.3000    4.7211

    9.1870    0.0000   18.1000    0.0000    0.7000    5.5360  100.0000    1.5804

    4.0974    0.0000   19.5800    0.0000    0.8710    5.4680  100.0000    1.4118

    2.1551    0.0000   19.5800    0.0000    0.8710    5.6280  100.0000    1.5166

    1.6286    0.0000   21.8900    0.0000    0.6240    5.0190  100.0000    1.4394



The data in tabular form: samples in rows, features in columns.

These ranges present difficulties

Neural networks have difficulty adapting to heterogeneous data 

The data will have to be **normalised**

These ranges present difficulties because neural networks have difficulty adapting to heterogeneous data. The data will have to be **normalised**